---
USERS:
  user1: { login: "user1", "email": "user1@local", "Fullname": "User 1", "workstation": "W1", "TimeZone": "-0500" }
  user2: { login: "user3", "email": "user2@local", "Fullname": "User 2", "workstation": "W2", "TimeZone": "-0500" }
  user3: { login: "user3", "email": "user3@local", "Fullname": "User 3", "workstation": "W3", "TimeZone": "-0500" }

TEMPLATES:
  #MAIL_SEND: "%TS% SEND %SUBJECT% %SENDER% %RCPT% %SIZE%"
  #MAIL_RECV: "%TS% RECV %SUBJECT% %SENDER% %RCPT% %SIZE%"
  MAIL_SEND: "%TS%,%CIP%,%CHOST%,%SIP%,%SHOST%,,,SMTP,SEND,%NUM%,<%MSGID%>,%RCPT%,,%SIZE%,%CNT%,,,%SUBJECT%,%SENDER%,%SENDER%,07I: NTS: ,Originating,,,,S:FirstForestHop"
  MAIL_RECV: "%TS%,%CIP%,%CHOST%,%SIP%,%SHOST%,,,SMTP,RECEIVE,%NUM%,<%MSGID%>,%RCPT%,,%SIZE%,1,,,%SUBJECT%,%SENDER%,%SENDER%,07I: NTS: ,Originating,,,,S:FirstForestHop"

REPLACERS:
  subjects: ["file", "common/subjects.txt"]

SCENARIOS:
  email_send_nrm:
  -
    templateid: "MAIL_SEND"
    timeformat: "%Y-%m-%d %H:%M:%S.000000"
    replaces:
      "%SENDER%":     ["user", "email"]
      "%SUBJECT%":    ["file", "common/subjects.txt"]
      "%CHOST%":      ["user", "workstation"]
      "%SHOST%":      ["file", "common/hosts.txt"]
      "%NUM%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%MSGID%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%SIZE%":
        - "py"
        - !!python/name:random.randint
        - [500, 4000]
      "%CIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%SIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%RCPT%,%CNT%":
        - "py"
        - !!python/name:common.utils.get_rcpt
        - [1, 3]

  email_recv_nrm:
  -
    templateid: "MAIL_RECV"
    timeformat: "%Y-%m-%d %H:%M:%S.000000"
    replaces:
      "%SUBJECT%":    ["file", "common/subjects.txt"]
      "%CHOST%":      ["file", "common/hosts.txt"]
      "%SHOST%":      ["file", "common/hosts.txt"]
      "%NUM%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%MSGID%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%SIZE%":
        - "py"
        - !!python/name:random.randint
        - [500, 4000]
      "%CIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%SIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%SENDER%":
        - "py"
        - !!python/name:common.utils.get_email
        - []
      "%RCPT%": ["user", "email"]

  email_send_abn_spam:
  -
    templateid: "MAIL_SEND"
    timeformat: "%Y-%m-%d %H:%M:%S.000000"
    replaces:
      "%SENDER%":     ["user", "email"]
      "%SUBJECT%":    ["file", "common/subjects.txt"]
      "%CHOST%":      ["user", "workstation"]
      "%SHOST%":      ["file", "common/hosts.txt"]
      "%NUM%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%MSGID%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%SIZE%":
        - "py"
        - !!python/name:random.randint
        - [500, 4000]
      "%CIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%SIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%RCPT%,%CNT%":
        - "py"
        - !!python/name:common.utils.get_rcpt
        - [1, 3]

  email_send_nrm_size:
  -
    templateid: "MAIL_SEND"
    timeformat: "%Y-%m-%d %H:%M:%S.000000"
    replaces:
      "%SENDER%":     ["user", "email"]
      "%SUBJECT%":    ["file", "common/subjects.txt"]
      "%CHOST%":      ["user", "workstation"]
      "%SHOST%":      ["file", "common/hosts.txt"]
      "%NUM%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%MSGID%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%SIZE%":
        - "py"
        - !!python/name:random.randint
        - [500000, 10000000]
      "%CIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%SIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%RCPT%,%CNT%":
        - "py"
        - !!python/name:common.utils.get_rcpt
        - [1, 3]

  email_send_abn_size:
  -
    templateid: "MAIL_SEND"
    timeformat: "%Y-%m-%d %H:%M:%S.000000"
    replaces:
      "%SENDER%":     ["user", "email"]
      "%SUBJECT%":    ["file", "common/subjects.txt"]
      "%CHOST%":      ["user", "workstation"]
      "%SHOST%":      ["file", "common/hosts.txt"]
      "%NUM%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%MSGID%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%SIZE%":
        - "py"
        - !!python/name:random.randint
        - [500000, 10000000]
      "%CIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%SIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%RCPT%,%CNT%":
        - "py"
        - !!python/name:common.utils.get_rcpt
        - [1, 3]

  email_send_abn_rcpt:
  -
    templateid: "MAIL_SEND"
    timeformat: "%Y-%m-%d %H:%M:%S.000000"
    replaces:
      "%SENDER%":     ["user", "email"]
      "%SUBJECT%":    ["file", "common/subjects.txt"]
      "%CHOST%":      ["user", "workstation"]
      "%SHOST%":      ["file", "common/hosts.txt"]
      "%NUM%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%MSGID%":
        - "py"
        - !!python/name:random.randint
        - [1000000, 5000000]
      "%SIZE%":
        - "py"
        - !!python/name:random.randint
        - [500000, 10000000]
      "%CIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%SIP%":
        - "py"
        - !!python/name:common.utils.get_random_ip
        - ["192.168.0.0/24"]
      "%RCPT%,%CNT%":
        - "py"
        - !!python/name:common.utils.get_rcpt
        - [1, 3]

ACTIVITY:
  user1:
    - [ "email_send_nrm",      ["* 8-18 * * 1-5",       3600, [1,2]] ]
    - [ "email_send_nrm",      ["* 0-8,18-24 * * 1-5", 50400, [1,2]] ]
    - [ "email_send_nrm",      ["* 0-24 * * 6,0",      86400, [1,2]] ]
    - [ "email_recv_nrm",      ["* 8-18 * * 1-5",       3600, [2,4]] ]
    - [ "email_recv_nrm",      ["* 0-8,18-24 * * 1-5", 50400, [4,8]] ]
    - [ "email_recv_nrm",      ["* 0-24 * * 6,0",      86400, [4,8]] ]
    - [ "email_send_nrm_size", ["* 8-18 * * 1-5",      36000, [1,2]] ]
    - [ "email_send_abn_spam", ["0-10 11 * * 1-5",       600, [100,500]] ]
    - [ "email_send_abn_size", ["* 17-18 * * 1-5",      3600, [5,10]] ]
    - [ "email_send_abn_rcpt", ["* 17-18 * * 1-5",      3600, [5,10]] ]
  user2:
    - [ "email_send_nrm",      ["* 8-18 * * 1-5",  3600, [1,2]] ]
    - [ "email_recv_nrm",      ["* 8-18 * * 1-5",  3600, [2,4]] ]
...
